### ISSUE TITLE
tcp_tw_recycle failed after installation

### ISSUE THREAD

**Issue by crapthings** [wavengine/shadowsocks-install#2]
vultr ubuntu 18.04

i have this print on console after installation what is wrong

sysctl: cannot stat /proc/sys/net/ipv4/tcp_tw_recycle: No such file or directory

**Comment by vndroid** [comment]
Hi,

This warning has no effect on usage. It is your Linux kernel not support some parameter.
if you worry about it. Please remove the parameter `net.ipv4.tcp_tw_recycle = 0` in `/etc/sysctl.conf`,then run
```bash
# sysctl -p
```
