### ISSUE TITLE
Multi accounts on the client side

### ISSUE THREAD

**Issue by amirmojiry** [wavengine/shadowsocks-install#4]
Thanks for this good script.
Can you tell me how I can create multiple accounts on the client side?

**Comment by vndroid** [comment]
Sorry, this script can not support multiple servers, if you need multiple accounts on the server-side, Multiple accounts are recommended to be deployed manually so that troubleshooting will be easier in the follow-up

**Comment by amirmojiry** [comment]
Thanks, but I meant multi username and password on the client-side so each person could connect with a specific username and password.

**Comment by MahdiAkrami01** [comment]
you can config like this for multiple users:

```
{
    "server": "0.0.0.0",
    "port_password": {
        "8381": "ps1",
        "8382": "ps2",
        "8383": "ps3",
        "8384": "ps4"
    },
    "timeout": 300,
    "method": "aes-256-cfb"
}
```
